---
title: "Issara_new_dataset"
author: "Boyu Liu"
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(plyr)
library(dplyr)
library(AER)
library(data.table)
library(stringr)
library(ivpack)
library(estimatr)

# library(mice)
# library(miceadds)


file_folder = '/Users/boyuliu/pyprojects/Joann/Joann-Thailand-Project/notebooks/datasets/new_dataset/'

weekly_data1 = read.csv(paste(file_folder, 'regression_data_wv_cases1_20210131.csv', sep=""), header = TRUE)
weekly_data2 = read.csv(paste(file_folder, 'regression_data_wv_cases2_20210131.csv', sep=""), header = TRUE)
weekly_data3 = read.csv(paste(file_folder, 'regression_data_wv_cases3_20210131.csv', sep=""), header = TRUE)
weekly_data4 = read.csv(paste(file_folder, 'regression_data_wv_cases4_20210131.csv', sep=""), header = TRUE)
weekly_data4_large = read.csv(paste(file_folder, 'regression_data_large_p_wv_cases4.csv', sep=""), header = TRUE)
# weekly_data1_lag = read.csv(paste(file_folder, 'regression_data_demand_shifted_wv_cases1.csv', sep=""), header = TRUE)
old_data = read.csv(paste(file_folder, 'to_compare.csv', sep=""), header = TRUE)

nwfe.1.1.1  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_1 -1, data=weekly_data1, clusters=province, diagnostics=TRUE)
summary(nwfe.1.1.1)

nwfe.1.1.2  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_2 -1, data=weekly_data1, clusters=province, diagnostics=TRUE)
summary(nwfe.1.1.2)

## best
nwfe.1.1.3  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data1, clusters=province, diagnostics=TRUE)
summary(nwfe.1.1.3)

# compare with old data
nwfe.1.1.4  <- iv_robust(perc_abuse ~ total_demand + Location -1 | Location + diff_cny_ex_rate_1 -1, data=old_data, clusters=Location, diagnostics=TRUE)
summary(nwfe.1.1.4)

# OLS
summary(estimatr::lm_robust(perc_abuse ~ total_demand + Location -1, old_data, clusters = Location))

# other datasets
nwfe.1.1.3  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data2, clusters=province, diagnostics=TRUE)
summary(nwfe.1.1.3)
## OLS
summary(estimatr::lm_robust(perc_abuse ~ total_demand + province -1, weekly_data2, clusters = province))

nwfe.1.1.3  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data3, clusters=province, diagnostics=TRUE)
summary(nwfe.1.1.3)
## OLS
summary(estimatr::lm_robust(perc_abuse ~ total_demand + province -1, weekly_data3, clusters = province))

nwfe.1.1.3  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data4, clusters=province, diagnostics=TRUE)
summary(nwfe.1.1.3)
## OLS
summary(estimatr::lm_robust(perc_abuse ~ total_demand + province -1, weekly_data4, clusters = province))

## ols
summary(estimatr::lm_robust(perc_abuse ~ total_demand + province -1, weekly_data1, clusters = province))

nwfe.1.2.1  <- iv_robust(perc_abuse ~ total_demand + province + month -1 | province + month + ex_rate_diff_3 -1, data=weekly_data1, clusters=province, diagnostics=TRUE)
summary(nwfe.1.2.1)

nwfe.1.2.2  <- iv_robust(perc_abuse ~ total_demand + province + quarter -1 | province + quarter + ex_rate_diff_3 -1, data=weekly_data1, clusters=province, diagnostics=TRUE)
summary(nwfe.1.2.2)

nwfe.1.3.1  <- iv_robust(perc_abuse ~ total_demand_lag1 + province -1 | province + ex_rate_diff_1 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.1)

nwfe.1.3.2  <- iv_robust(perc_abuse ~ total_demand_lag1 + province -1 | province + ex_rate_diff_2 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.2)

nwfe.1.3.3  <- iv_robust(perc_abuse ~ total_demand_lag1 + province -1 | province + ex_rate_diff_3 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.3)

nwfe.1.3.4  <- iv_robust(perc_abuse ~ total_demand_lag1 + province -1 | province + ex_rate_diff_4 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.4)

nwfe.1.3.5  <- iv_robust(perc_abuse ~ total_demand_lag2 + province -1 | province + ex_rate_diff_2 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.5)

nwfe.1.3.6  <- iv_robust(perc_abuse ~ total_demand_lag2 + province -1 | province + ex_rate_diff_3 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.6)

nwfe.1.3.7  <- iv_robust(perc_abuse ~ total_demand_lag2 + province -1 | province + ex_rate_diff_4 -1, data=weekly_data1_lag, clusters=province, diagnostics=TRUE)
summary(nwfe.1.3.7)

## data set 2
nwfe.2  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data2, clusters=province, diagnostics=TRUE)
summary(nwfe.2)

nwfe.3  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data3, clusters=province, diagnostics=TRUE)
summary(nwfe.3)

nwfe.4  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data4, clusters=province, diagnostics=TRUE)
summary(nwfe.4)

nwfe.4.1  <- iv_robust(perc_abuse ~ total_demand + province -1 | province + ex_rate_diff_3 -1, data=weekly_data4_large, clusters=province, diagnostics=TRUE)
summary(nwfe.4.1)

# ols
summary(estimatr::lm_robust(perc_abuse ~ total_demand + province -1, weekly_data4_large, clusters = province))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
